@startuml

state Priprava {
    state LoadTutorial
    state CheckTutorialData
    state DisplayTaskInPanel
    state case <<choice>>
    state Testiranje <<exitPoint>>
    state Branje <<exitPoint>>

    [*] --> LoadTutorial
    LoadTutorial --> ErrorDialog : Tutorial ni bil najden ali \n neuspešna destirilizacija 
    LoadTutorial : .json -> TutorialData objekt
    LoadTutorial --> DisplayTaskInPanel
    DisplayTaskInPanel: prikaz naslova in opisa tutoriala na ekranu
    DisplayTaskInPanel --> CheckTutorialData 
    CheckTutorialData : preveri ustroznost podatkov iz .json
    CheckTutorialData : prikaz prvega oblačka na ekranu (če obstaja)
    CheckTutorialData --> case
    case --> Branje : [oblački.Count > 2]
    case --> Testiranje : [oblački.Count <= 1 & test.Count > 0]
    case --> LoadTutorial : [oblački.Count <= 1 & test.Count = 0]

  CheckTutorialData -[hidden]-> ErrorDialog  
  ErrorDialog --> [*]
  ErrorDialog : prikaz napake uporaniku
}

@enduml
